apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-java-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-java-app
  template:
    metadata:
      name: tech-challenge-java-app
      labels:
        app: tech-challenge-java-app
    spec:
      containers:
      - name: tech-challenge-java-pod
        image: grunbruno/java-app-fase-4:1.0
        envFrom:
        - configMapRef:
            name: app-configmap
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet: 
            path: /order
            port: 80
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        readinessProbe:
          httpGet: 
            path: /order
            port: 80
          periodSeconds: 10
          failureThreshold: 6
          initialDelaySeconds: 10
        resources:
          requests: 
            cpu: 40m
