apiVersion: v1
kind: Service
metadata:
  name: svc-java-tech-challenge
spec:
  selector:
    app: tech-challenge-java-app
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080  